Adding short framework intro and section
searhein/trilinos-paper pull request #27
Opened 2023-08-01 16:51 UTC by jwillenbring

This PR adds a short framework intro and section along with a few references.

2023-08-01 16:52 UTC, jwillenbring commented
@srajama1 @ccober6 

I added a short section for the framework. We should possibly add more, but I don't know exactly what would be considered interesting and in scope for this paper for the intended audience.

2023-08-01 20:31 UTC, mayrmt requested changes

2023-08-01 20:31 UTC, mayrmt commented on framework.tex
> +The Framework is also responsible for maintaining the general infrastructure forthe Trilinos web site, wiki, and Doxygen documentation. The Framework owns some of the documented workflows on these si
```suggestion
The Framework is also responsible for maintaining the general infrastructure for the Trilinos web site, wiki, and Doxygen documentation. The Framework owns some of the documented workflows on these sites, such as the process for reproducing testing failures, but the Trilinos package developers own all of the documentation associated with their associated packages.
```

2023-08-01 20:31 UTC, mayrmt commented on framework.tex
> +Teuchos provides a suite of common tools for many Trilinos packages. These tools include memory management classes~\cite{bartlett2010} such as "smart" pointers and arrays, "parameter lists" for commu
Latex-compatible quotation marks:
```suggestion
Teuchos provides a suite of common tools for many Trilinos packages. These tools include memory management classes~\cite{bartlett2010} such as ``smart'' pointers and arrays, ``parameter lists'' for communicating hierarchical lists of parameters between library or application layers, templated wrappers for the BLAS and LAPACK, XML parsers, and other utilities. They provide a unified ``look and feel'' across Trilinos packages, and help avoid common programming mistakes.
```

2023-08-04 11:36 UTC, mayrmt approved these changes

2023-08-04 17:59 UTC, merged